version: '3.7'

x-common-variables: &common-variables
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}

services:
  database:
    image: mariadb:10.9.3
    restart: on-failure
    cap_add:
      - SYS_NICE
    volumes:
      - database:/var/lib/mysql
    networks:
      - network
    # don't leave the port open on production, this is just to help during development
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_HOST}

  nginx:
    image: nginx:1.23.1
    depends_on:
      - backend
    restart: on-failure
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - network
    ports:
      - "8080:80"

  frontend:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: "./frontend"
    depends_on:
      - backend
    networks:
      - network

  backend:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - database
    networks:
      - network
    environment: 
      ASPNETCORE_URLS: http://+:5062

volumes:
  database:

networks:
  network:
